<Project>
  <PropertyGroup>
    <Sts2Dir>E:\SteamLibrary\steamapps\common\Slay the Spire 2</Sts2Dir>
    <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
    <GodotExe>D:\Program\Godot\Godot_v4.5.1-stable_mono_win64_console.exe</GodotExe>
    <RitsuLibDeployDir>$(Sts2Dir)\mods\STS2-RitsuLib</RitsuLibDeployDir>
  </PropertyGroup>
</Project>
